import '@rp/ui/globals.css';

import { Providers } from '@/components/providers';
import type { Metadata } from 'next';

export const metadata: Metadata = {
        title: 'Create Next App',
        description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
                <html lang="en" suppressHydrationWarning>
                        <body className="font-sans antialiased">
                                <Providers>{children}</Providers>
                        </body>
                </html>
        );
}
